### ISSUE TITLE
Log fileSizes as Integers and not Strings

### ISSUE THREAD

**Issue by purukaushik** [FrancescoSTL/Site-Sonar#23]
Change '-' to Nulls. Maybe we can get MongoDB to eat the null integer and ignore them during aggregation queries.

**Comment by FrancescoSTL** [comment]
Fixed in #24

**Comment by purukaushik** [comment]
`fileSize` is still not aggregate-able cause it is a string 😞 
it has to be a `Number` like assetCompleteTIme
check [this](http://stackoverflow.com/questions/25853557/mongodb-parsefloat-for-string-field-in-aggregate-function-avg) and [this](https://docs.mongodb.com/manual/reference/operator/aggregation/avg/#non-numeric-values)

![scrn](http://i.imgur.com/kTCFbSc.png)

**Comment by FrancescoSTL** [comment]
Fixed in #24
